name: Semgrep SAST

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep CI
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"
          # Optional: generate SARIF report for GitHub Code Scanning
          # generateSarif: "1"
        # We allow it to continue on error so the other steps and workflows can run.
        continue-on-error: true
